spring:
  redis:
    host: localhost
    port: 6379
  session:
    # Redis 세션 설정 (spring-session-data-redis가 읽음)
    timeout: 30m

notification:
  channel: findmypet-notifications

server:
  port: 8081