spring:
  redis:
    host: localhost
    port: 6379
  session:
    # Redis 세션 설정 (spring-session-data-redis가 읽음)
    store-type: redis
    timeout: 30m
    cookie:
      name: SESSION
      encoding: none
    redis:
      namespace: findmypet:sessions
  datasource:
    url: jdbc:mysql://localhost:3306/findmypet
    username: root
    password: 3823
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

notification:
  channel: findmypet-notifications