spring:
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
  session:
    # Redis 세션 설정 (spring-session-data-redis가 읽음)
    store-type: redis
    timeout: 30m
    cookie:
      name: SESSION
      encoding: none
    redis:
      namespace: findmypet:sessions
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

notification:
  channel: findmypet-notifications

# S3
aws:
  region: ap-northeast-1
  credentials:
    access-key: ${AWS_ACCESS_KEY}
    secret-key: ${AWS_SECRET_KEY}
  s3:
    bucket: s3-findmypet
